examples(
    [
        % example01 SIMPLE
        ex(
            1,
            eggs(
                s(
                    [
                        [white,blue,black,black,orange],
                        [white,red,white,orange,black],
                        [orange,orange,blue,red,white],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty]],
                    [[white,blue,orange,white,orange]],
                    [],
                    []
                ),
                _
            )
        ),

        % example02 SIMPLE
        ex(
            2,
            eggs(
                s(
                    [
                        [black,orange,red,white,orange],
                        [white,red,white,blue,black],
                        [orange,blue,blue,red,black],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty]],
                    [[black,white,orange,red,blue]],
                    [],
                    []
                ),
                _
            )
        ),

        % example03 SIMPLE
        ex(
            3,
            eggs(
                s(
                    [
                        [black,black,white,black,blue],
                        [orange,red,blue,orange,black],
                        [black,orange,blue,red,white],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty]],
                    [[black,black,orange,white,red]],
                    [],
                    []
                ),
                _
            )
        ),

        % example04 SIMPLE
        ex(
            4,
            eggs(
                s(
                    [
                        [black,black,white,black,blue],
                        [orange,red,blue,orange,black],
                        [black,orange,blue,red,white],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty]],
                    [[black,blue,orange,white,red]],
                    [],
                    []
                ),
                _
            )
        ),

        % example05 SIMPLE
        ex(
            5,
            eggs(
                s(
                    [
                        [white,orange,white,white,blue,orange,black,red],
                        [red,blue,black,orange,white,red,blue,blue],
                        [],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty]],
                    [[white,orange,red,white,blue,black]],
                    [],
                    []
                ),
                _
            )
        ),

        % example06 SIMPLE
        ex(
            6,
            eggs(
                s(
                    [
                        [white,white,red,blue,black,orange,black,red],
                        [red,blue,red,orange,white,red,blue,blue],
                        [],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty]],
                    [[white,white,red,red,blue,blue]],
                    [],
                    []
                ),
                _
            )
        ),

        % example07 SIMPLE
        ex(
            7,
            eggs(
                s(
                    [
                        [white,blue,black,red,black,orange,black,red],
                        [blue,blue,blue,orange,white,red,blue,blue],
                        [],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty]],
                    [[white,blue,black,red,blue,blue]],
                    [],
                    []
                ),
                _
            )
        ),

        % example08 SIMPLE
        ex(
            9,
            eggs(
                s(
                    [
                        [orange,white,red,orange,white,black,blue,orange,blue,black],
                        [blue,white,white,black,red,orange,white,blue,white,black],
                        [blue,black,black,red,blue,white,blue,black,red,red],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty]],
                    [[orange,white,blue,black,blue,black,white]],
                    [],
                    []
                ),
                _
            )
        ),

        % example16 SIMPLE
        ex(
            16,
            eggs(
                s(
                    [
                        [white,white,blue,blue,red,white,blue,orange,orange,black],
                        [orange,black,black,orange,black,white,orange,black,white,red],
                        [orange,red,black,white,red,red,black,white,red,black],
                        [blue,blue,orange,white,blue,blue,white,black,black,blue],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[blue,white,orange,blue,white,black,orange,red]],
                    [],
                    []
                ),
                _
            )
        ),

        % example17 SIMPLE
        ex(
            17,
            eggs(
                s(
                    [
                        [white,red,black,blue,orange,black,red,red],
                        [orange,orange,white,white,red,orange,blue,black],
                        [white,orange,white,orange,blue,white,black,orange],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty]],
                    [[orange,orange,white,orange,white,red]],
                    [],
                    []
                ),
                _
            )
        ),

        % example20 SIMPLE
        ex(
            20,
            eggs(
                s(
                    [
                        [blue,orange,black,blue,orange,black,red,red],
                        [blue,black,red,white,red,orange,blue,black],
                        [blue,orange,blue,black,black,orange,black,orange],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty]],
                    [[blue,orange,blue,black,black,orange]],
                    [],
                    []
                ),
                _
            )
        ),

        % example08 MEDIUM
        ex(
            8,
            eggs(
                s(
                    [
                        [orange,black,orange,white,black,black,blue,orange,blue,black],
                        [black,orange,white,black,red,orange,white,blue,white,black],
                        [black,white,white,red,blue,white,blue,black,red,red],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty]],
                    [[orange,black,orange,white,black,white,white]],
                    [],
                    []
                ),
                _
            )
        ),

        % example10 MEDIUM
        ex(
            10,
            eggs(
                s(
                    [
                        [black,white,black,white,blue,black,black,orange,blue,black],
                        [black,white,white,black,black,orange,white,blue,white,black],
                        [black,white,black,blue,blue,white,blue,black,red,red],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty]],
                    [[black,white,black,white,white,black,blue]],
                    [],
                    []
                ),
                _
            )
        ),

        % example11 MEDIUM
        ex(
            11,
            eggs(
                s(
                    [
                        [white,black,black,orange,blue,black,black,orange,blue,red],
                        [white,orange,black,black,black,orange,red,blue,white,black],
                        [white,white,black,orange,blue,white,blue,black,red,red],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty]],
                    [[white,black,white,orange,black,orange,white]],
                    [],
                    []
                ),
                _
            )
        ),

        % example12 MEDIUM
        ex(
            12,
            eggs(
                s(
                    [
                        [black,red,black,black,red,white,blue,orange,orange,black],
                        [orange,white,blue,orange,black,white,orange,black,white,red],
                        [blue,red,blue,white,red,red,black,white,red,black],
                        [black,red,orange,red,black,blue,white,black,black,blue],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[black,red,orange,white,blue,black,black,red]],
                    [],
                    []
                ),
                _
            )
        ),

        % example13 MEDIUM
        ex(
            13,
            eggs(
                s(
                    [
                        [black,black,black,black,red,white,blue,orange,orange,black],
                        [orange,orange,orange,orange,black,white,orange,black,white,red],
                        [black,orange,black,blue,red,red,black,white,red,black],
                        [orange,blue,black,red,black,blue,white,black,black,blue],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[orange,blue,orange,black,orange,black,blue,orange]],
                    [],
                    []
                ),
                _
            )
        ),

        % example14 MEDIUM
        ex(
            14,
            eggs(
                s(
                    [
                        [white,orange,red,blue,red,white,blue,orange,orange,black],
                        [blue,red,orange,orange,black,white,orange,black,white,red],
                        [blue,blue,orange,white,red,red,black,white,red,black],
                        [white,orange,blue,blue,black,blue,white,black,black,blue],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[white,orange,blue,red,orange,blue,red,orange]],
                    [],
                    []
                ),
                _
            )
        ),

        % example15 MEDIUM
        ex(
            15,
            eggs(
                s(
                    [
                        [orange,black,white,blue,red,white,blue,orange,orange,black],
                        [red,black,red,orange,black,white,orange,black,white,red],
                        [white,blue,orange,white,red,red,black,white,red,black],
                        [white,blue,blue,blue,black,blue,white,black,black,blue],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[white,blue,orange,red,blue,black,red,white]],
                    [],
                    []
                ),
                _
            )
        ),

        % example18 MEDIUM
        ex(
            18,
            eggs(
                s(
                    [
                        [white,red,orange,blue,orange,black,red,red],
                        [black,orange,white,white,red,orange,blue,black],
                        [white,red,black,blue,blue,white,black,orange],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty]],
                    [[white,red,white,black,orange,blue]],
                    [],
                    []
                ),
                _
            )
        ),

        % example19 MEDIUM
        ex(
            19,
            eggs(
                s(
                    [
                        [blue,white,orange,blue,orange,black,red,red],
                        [black,white,red,white,red,orange,blue,black],
                        [white,black,red,blue,blue,white,black,orange],
                        [],
                        []
                    ],
                    [[empty,empty,empty,empty,empty,empty]],
                    [[blue,white,black,orange,white,red]],
                    [],
                    []
                ),
                _
            )
        ),

        % example21 MEDIUM
        ex(
            21,
            eggs(
                s(
                    [
                        [black,blue,red,white,blue,white,white,blue,red,orange,blue],
                        [blue,white,red,black,black,orange,red,orange,blue,blue,white],
                        [red,white,white,black,red,red,orange,blue,orange,blue,white],
                        [white,orange,red,blue,black,white,red,white,orange,blue,black],
                        [white,red,white,blue,orange,black,white,white,black,orange,red]
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[red,black,white,blue,red,orange,white,white,blue,black]],
                    [],
                    []
                ),
                _
            )
        ),

        % example23 MEDIUM
        ex(
            23,
            eggs(
                s(
                    [
                        [orange,white,black,blue,black,white,white,blue,red,orange,blue],
                        [white,black,white,orange,red,orange,red,blue,blue,white],
                        [black,red,black,blue,white,red,orange,blue,orange,blue,white],
                        [black,black,orange,orange,black,white,red,white,orange,blue,black],
                        [blue,orange,black,red,orange,black,white,white,black,orange,red]
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[white,orange,white,black,blue,red,orange,black,white,orange]],
                    [],
                    []
                ),
                _
            )
        ),

        % example22 HARD
        ex(
            22,
            eggs(
                s(
                    [
                        [orange,red,red,white,black,white,white,blue,red,orange,blue],
                        [red,orange,red,black,black,orange,red,orange,blue,blue,white],
                        [orange,blue,black,blue,white,red,orange,blue,orange,blue,white],
                        [white,orange,blue,orange,black,white,red,white,orange,blue,black],
                        [white,blue,blue,red,orange,black,white,white,black,orange,red]
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[red,orange,white,blue,white,red,red,orange,blue,black]],
                    [],
                    []
                ),
                _
            )
        ),

        % example24 HARD
        ex(
            24,
            eggs(
                s(
                    [
                        [white,red,orange,white,black,white,white,blue,red,orange,blue],
                        [blue,red,white,orange,red,orange,red,orange,blue.blue,white],
                        [white,white,blue,orange,blue,red,orange,blue,orange,blue,white],
                        [white,blue,black,red,black,white,red,white,orange,blue,black],
                        [blue,black,orange,orange,orange,black,white,white,black,orange,red]
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[white,red,white,blue,orange,white,black,red,blue,black]],
                    [],
                    []
                ),
                _
            )
        ),

        % example25 HARD
        ex(
            25,
            eggs(
                s(
                    [
                        [blue,orange,black,white,black,white,white,blue,red,orange,blue],
                        [blue,black,white,orange,red,orange,red,orange,blue,blue,white],
                        [black,red,black,black,blue,red,orange,blue,orange,blue,white],
                        [blue,black,black,red,white,white,red,white,orange,blue,black],
                        [orange,white,blue,red,orange,black,white,white,black,orange,red]
                    ],
                    [[empty,empty,empty,empty,empty,empty,empty,empty,empty,empty]],
                    [[orange,white,blue,orange,blue,black,red,black,black,red]],
                    [],
                    []
                ),
                _
            )
        )

    ]/[]
).